### ISSUE TITLE
MRU dimensional transceiver issue

### ISSUE THREAD

**Issue by TheMadmanofChaos** [Modbder/EssentialThaumaturgy#1]
Forge: 10.13.3.1428
Essential craft 3: 4.5.1710.222
Dummy core:1.13
EssentialThaumaturgy-1.1.1710.11EC(4.4.1710.37)TC(4.2.3.5)
Thaumcraft 4.2.3.5

MRU dimensional transceiver is causing this issue to be reported in the console. Unsure if it is related, but it seems to be messing with the MRU containment chamber it is linked too, causing the MRUCU to despawn and the chamber to stop functioning.

[09:15:30] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
    at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:230) [mn.class:?]
    at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:152) [mn.class:?]
    at net.minecraft.world.WorldManager.func_72703_a(SourceFile:31) [mp.class:?]
    at net.minecraft.world.World.func_72923_a(World.java:1347) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:844) [mt.class:?]
    at net.minecraft.world.World.func_72868_a(World.java:3304) [ahb.class:?]
    at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:921) [apx.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
    at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
    at net.minecraft.world.World.func_147438_o(World.java:2536) [ahb.class:?]
    at essentialThaumaturgy.common.tile.TileMRUDimensionalTranciever.mruIn(TileMRUDimensionalTranciever.java:101) [TileMRUDimensionalTranciever.class:?]
    at essentialThaumaturgy.common.tile.TileMRUDimensionalTranciever.mruIn(TileMRUDimensionalTranciever.java:71) [TileMRUDimensionalTranciever.class:?]
    at essentialThaumaturgy.common.tile.TileMRUDimensionalTranciever.func_145845_h(TileMRUDimensionalTranciever.java:46) [TileMRUDimensionalTranciever.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
    at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:196) ~[mn.class:?]
    ... 26 more

**Comment by Modbder** [comment]
It seems like the Dimensional Tranciever is constantly making MC load up the world it is recieving the power from. Is the world constantly loaded?

**Comment by TheMadmanofChaos** [comment]
The location it is receiving power from isn't loaded. My temporary system couldn't handle the power draw, so I moved a MRU Tesla reactor to the quarry instead of warping it in. The chunkloader ran out of power, and I hadn't removed the dimensional tranciever until I saw this issue.

Also, might this be linked to https://github.com/Modbder/EssentialCraft3/issues/7 ? After breaking the dimensional tranciever the crash has stopped occurring.

**Comment by Modbder** [comment]
It might be, but the issue #7 still needs a fix ;) I think, that I might have fixed that, but I need more testing.

**Comment by TheMadmanofChaos** [comment]
Alright good to know. I thank you for the quick response to these issues.

**Comment by LemADEC** [comment]
Is it still a thing?
